[package]
name = "axpindexer-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "AXPIndexerClient"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axpindexer-core = { path = "../core" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tiny_http = "0.12"
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
