[package]
name = "axpindexer-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "AXPIndexerDaemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axpindexer-core = { path = "../core" }
clap.workspace = true
sha2.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
